version: 0.2
#testing abc
phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo #{SourceVariables.CommitMessage}
      - echo Logging in to Amazon ECR...
      - aws --version
      - cd preinstall
      - chmod 777 preinstall.sh
      - ./preinstall.sh adoptopenjdk 16_36-jre-hotspot
      - cd ..
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI_PRODUCT=243626120307.dkr.ecr.ap-southeast-1.amazonaws.com/product
      - REPOSITORY_URI_REVIEW=243626120307.dkr.ecr.ap-southeast-1.amazonaws.com/review
      - REPOSITORY_URI_RECOMMENDATION=243626120307.dkr.ecr.ap-southeast-1.amazonaws.com/recommendation
      - REPOSITORY_URI_PRODUCT_COMPOSITE=243626120307.dkr.ecr.ap-southeast-1.amazonaws.com/product_composite
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
#      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - cd Chapter06
      - ./gradlew --version
      - java --version
      - ./gradlew build --no-scan
      - docker-compose -f docker-compose-ecs.yml build
      - docker tag ecs_product:latest $REPOSITORY_URI_PRODUCT:$IMAGE_TAG
      - docker tag ecs_review:latest $REPOSITORY_URI_REVIEW:$IMAGE_TAG
      - docker tag ecs_recommendation:latest $REPOSITORY_URI_RECOMMENDATION:$IMAGE_TAG
      - docker tag ecs_product-composite:latest $REPOSITORY_URI_PRODUCT_COMPOSITE:$IMAGE_TAG
      - docker tag ecs_product:latest $REPOSITORY_URI_PRODUCT:latest
      - docker tag ecs_review:latest $REPOSITORY_URI_REVIEW:latest
      - docker tag ecs_recommendation:latest $REPOSITORY_URI_RECOMMENDATION:latest
      - docker tag ecs_product-composite:latest $REPOSITORY_URI_PRODUCT_COMPOSITE:latest
#      - echo Build started on `date`
#      - echo Building the Docker image...
#      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
#      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI_PRODUCT:latest
      - docker push $REPOSITORY_URI_REVIEW:latest
      - docker push $REPOSITORY_URI_RECOMMENDATION:latest
      - docker push $REPOSITORY_URI_PRODUCT_COMPOSITE:latest
      - docker push $REPOSITORY_URI_PRODUCT:$IMAGE_TAG
      - docker push $REPOSITORY_URI_REVIEW:$IMAGE_TAG
      - docker push $REPOSITORY_URI_RECOMMENDATION:$IMAGE_TAG
      - docker push $REPOSITORY_URI_PRODUCT_COMPOSITE:$IMAGE_TAG
#      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - echo Writing image definitions file...
      - cd ..
      - printf '[{"name":"product-service","imageUri":"%s"}]' $REPOSITORY_URI_PRODUCT:$IMAGE_TAG > product.json
      - printf '[{"name":"review-service","imageUri":"%s"}]' $REPOSITORY_URI_REVIEW:$IMAGE_TAG > review.json
      - printf '[{"name":"recommendation-service","imageUri":"%s"}]' $REPOSITORY_URI_RECOMMENDATION:$IMAGE_TAG > recommendation.json
      - printf '[{"name":"product-composite-service","imageUri":"%s"}]' $REPOSITORY_URI_PRODUCT_COMPOSITE:$IMAGE_TAG > product_composite.json
#      - printf "" > product_composite.json
      - cat product.json
      - cat review.json
      - cat recommendation.json
      - cat product_composite.json
artifacts:
  files:
    - product_composite.json
    - recommendation.json
    - review.json
    - product.json
