version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI_PRODUCT=243626120307.dkr.ecr.ap-southeast-1.amazonaws.com/product
      - REPOSITORY_URI_REVIEW=243626120307.dkr.ecr.ap-southeast-1.amazonaws.com/review
      - REPOSITORY_URI_RECOMMENDATION=243626120307.dkr.ecr.ap-southeast-1.amazonaws.com/recommendation
      - REPOSITORY_URI_PRODUCT_COMPOSITE=243626120307.dkr.ecr.ap-southeast-1.amazonaws.com/product_composite
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
#      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - cd Chapter04
      - ./gradlew --version
      - java --version
      - ./gradlew build --no-scan
      - docker-compose build
      - docker tag chapter04_product:latest $REPOSITORY_URI_PRODUCT:$IMAGE_TAG
      - docker tag chapter04_review:latest $REPOSITORY_URI_REVIEW:$IMAGE_TAG
      - docker tag chapter04_recommendation:latest $REPOSITORY_URI_RECOMMENDATION:$IMAGE_TAG
      - docker tag chapter04_product-composite:latest $REPOSITORY_URI_PRODUCT_COMPOSITE:$IMAGE_TAG
      - docker tag chapter04_product:latest $REPOSITORY_URI_PRODUCT:latest
      - docker tag chapter04_review:latest $REPOSITORY_URI_REVIEW:latest
#      - echo Build started on `date`
#      - echo Building the Docker image...
#      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
#      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
#      - docker push $REPOSITORY_URI_PRODUCT:latest
#      - docker push $REPOSITORY_URI_REVIEW:latest
      - docker push $REPOSITORY_URI_PRODUCT:$IMAGE_TAG
      - docker push $REPOSITORY_URI_REVIEW:$IMAGE_TAG
      - docker push $REPOSITORY_URI_RECOMMENDATION:$IMAGE_TAG
      - docker push $REPOSITORY_URI_PRODUCT_COMPOSITE:$IMAGE_TAG
#      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"product-service","imageUri":"%s"}]' $REPOSITORY_URI_PRODUCT:$IMAGE_TAG > product.json
      - printf '[{"name":"product-service","imageUri":"%s"}]' $REPOSITORY_URI_REVIEW:$IMAGE_TAG > review.json
      - printf '[{"name":"product-service","imageUri":"%s"}]' $REPOSITORY_URI_RECOMMENDATION:$IMAGE_TAG > recommendation.json
      - printf '[{"name":"product-service","imageUri":"%s"}]' $REPOSITORY_URI_PRODUCT_COMPOSITE:$IMAGE_TAG > product_composite.json
      - cat product.json
      - cat review.json
      - cat recommendation.json
      - cat product_composite.json
artifacts:
  files:
    - product.json
    - review.json
    - recommendation.json
    - product_composite.json
