server.port: 7002
server.error.include-message: always

#spring.data.mongodb:
#  host: localhost
#  port: 27017
#  database: recommendation-db

spring.data.mongodb:
  uri: mongodb://quangchu:mongodb123$@docdb-2023-03-14-13-50-53.cluster-cltvrdi2i5ee.ap-southeast-1.docdb.amazonaws.com:27017/?replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false
  database: recommendation-db

logging:
  level:
    root: INFO
    se.magnus: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

---
spring.config.activate.on-profile: docker

server.port: 8080

spring.data.mongodb.host: mongodb
